### PR TITLE
Methods marked as final can't be private in PHP 8+

### PR DESCRIPTION
**Pull request by alfredbez**
## PR Description

Fixes the problem reported in https://github.com/spryker/code-sniffer/issues/241#issuecomment-814062652

## Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

### CODE REVIEW

**Comment by dereuromark** [comment]
How does that improve the current code?

**Comment by alfredbez** [comment]
With the latest version of the code-sniffer:
```
abez@abez-XPS-15-9500:~/projects/myproject/current$ cat src/Pyz/Zed/Foo.php
<?php declare(strict_types = 1);

namespace Pyz\Zed\;

class Foo
{
    /**
     * @return void
     */
    final protected function bar()
    {
    }
}
abez@abez-XPS-15-9500:~/projects/myproject/current$ vendor/bin/phpcs --standard=config/ruleset.xml src/Pyz/Zed/Foo.php
E 1 / 1 (100%)



FILE: /home/abez/projects/myproject/current/src/Pyz/Zed/Foo.php
-----------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------------------------------------
 1 | ERROR | The final declaration requires public visibility for PHP 8+
   |       | (Spryker.Classes.MethodDeclaration.FinalVisibility)
-----------------------------------------------------------------------------------------------------------------------------

Time: 90ms; Memory: 32.73MB
```

With the provided fix:
```
abez@abez-XPS-15-9500:~/projects/myproject/current$ vendor/bin/phpcs --standard=config/ruleset.xml src/Pyz/Zed/Foo.php
. 1 / 1 (100%)


Time: 106ms; Memory: 32.73MB
```

It will only report an error if a method is `private` and `final`, but not if the method is `protected` and `final`. Have you checked [this comment](https://github.com/spryker/code-sniffer/issues/241#issuecomment-814062652)?

**Comment by dereuromark** [comment]
Isn't the point of this to only allow public visibility? Protected is currently also excluded, and afaik this is as expected, no?

**Comment by dereuromark** [comment]
I see your point that it technically could be loosened, but in our current quality spectrum, we do not desire to use it as such.
We will have to talk about whether we want to allow this for project code - which the risk of it being used (again) where we do not see the value in it.

**Comment by alfredbez** [comment]
btw, here's [the RFC](https://wiki.php.net/rfc/inheritance_private_methods) and the [discussion from the mailing list](https://externals.io/message/110540) regarding this change.

**Pull request merged**
