### PR TITLE
Fix DisallowArrayTypeHintSyntaxSniff

### PR DESCRIPTION
**Pull request by szepeviktor**
Shot in the dark!! ⚫

### CODE REVIEW

**Comment by dereuromark** [comment]
Do u have a test case or an example to reproduce?

**Comment by szepeviktor** [comment]
Yes. CI output in the other PR.
https://github.com/spryker/code-sniffer/runs/6734257001?check_suite_focus=true

**Comment by szepeviktor** [comment]
I'm not a user/developer.
Just sending random PR-s!

**Comment by szepeviktor** [comment]
Thank you.

**Pull request merged**
