### PR TITLE
TE-9485 Code Sniffer | Constant vs string

### PR DESCRIPTION
**Pull request by dmytro-dymarchuk**
Ticket: https://spryker.atlassian.net/browse/TE-9485

Core PR: https://github.com/spryker/spryker/pull/8512

### CODE REVIEW

**Comment by dereuromark** [comment]
This should be an arch sniffer rule instead!

**Review by dereuromark — CHANGES_REQUESTED** [review]
Can you please show the changes in spryker and spryker-shop that are needed for this? And link from them to this PR?

**Comment by dmytro-dymarchuk** [comment]
> Can you please show the changes in spryker and spryker-shop that are needed for this? And link from them to this PR?

Core PR is attached

**Comment by dereuromark** [comment]
What about other scalar values?
I still think that this sounds more like some arch sniffer, but even here following such a rule to the teeth can create more an anti pattern
Who was the requester of this topic? 

As there are other actual high prior topics for arch sniffer on the agenda right now.

**Comment by dmytro-dymarchuk** [comment]
We discussed with @gechetspr only strings. Initially, I received this task from @pedrospry.

**Pull request closed without merging**
