### PR TITLE
Allow repo specific license for non Spryker files.

### PR DESCRIPTION
**Pull request by dereuromark**
Closes https://github.com/spryker/code-sniffer/issues/68

3 levels:

- /vendor/spryker/spryker/Bundles/[ModuleName]
- /vendor/vendor-name/project-name/
- /

for .license support

### CODE REVIEW

**Comment by darius-telycenas** [comment]
Looks good, just somewhere it should be mentioned that `.license` file **MUST** contain customer license formatted as **PHP comment**.

Another way would be to have `.license` file as:
```
line 1
line 2
```
…and sniffer then could parse it into:
```
/**
 * line 1
 * line 2
 */
```

**Comment by dereuromark** [comment]
I think it is easier for us to use the current approach (it is also way faster). And speed for a large amount of code base is probably a factor here.
Do you see any problem with only supporting the current one?

I agree, I will start docs here for both academy and the repo here itself now.

**Comment by darius-telycenas** [comment]
If a file would be named `.license.php` (just like in `project/.idea/fileTemplates/includes/PHP Function Doc Comment.php`) then it would be obvious that some `PHP` formatting is expected.  Otherwise, even https://github.com/spryker/demoshop/blob/master/LICENSE is just a plain text file.

**Comment by dereuromark** [comment]
It is a custom Spryker Code Sniffer dot file :) I think we can expect them to read the docs here on how to use.

**Pull request merged**
